### ISSUE TITLE
Right click on pan to reset to middle?

### ISSUE THREAD

**Issue by mxmilkiib** [jack-mixer/jack_mixer#10]
Or maybe middle click?

**Comment by SpotlightKid** [comment]
Or double click or Ctrl + left click. So many options :)

Anyway, should be consistent with shortcuts used elsewhere, e.g. there could also be a reset volume fader to 0 dB function using the same mouse click / modifier.

**Comment by dsheeler** [comment]
Think I will go with double click because that’s what I’m used to from zyn. I was wondering about volume: should it reset to 0db or -inf?

**Comment by SpotlightKid** [comment]
> I was wondering about volume: should it reset to 0db or -inf?

Since you already have the mute function to silence a channel, I think reset to 0 dB makes more sense.

**Comment by dsheeler** [comment]
I agree it should be 0 dB also because a slider can always be dragged to -inf easily, but hitting exactly 0 dB on a scale where 0 dB is somewhere in the middle of the fader position wouldn't be as easy

**Comment by SpotlightKid** [comment]
I wonder whether it would be overkill to make the kind of click to trigger "reset to default" an option (with two or three choices)? Double-click is the most convenient, because you need so second hand or button, and it also works on touch interfaces. But its also the most easy to trigger accidentally, And accidentally setting a channel to 0 dB, i.e let the full input signal level through, could be dangerous or at least unpleasant.

**Comment by mxmilkiib** [comment]
To both 0 and -inf would be nice. I've no opinion at this time on the actual methods :)

**Comment by dsheeler** [comment]
What do you think of double click on fader going to -inf, control double click on fader to 0dB, and double click on balance to 0?

**Comment by dsheeler** [comment]
I think the option thing is overkill for me... or am I just too lazy to implement???

**Comment by SpotlightKid** [comment]
Would work for me.

**Comment by dsheeler** [comment]
Settled on fader double click -> - inf, fader ctrl click -> 0dB, and balance double click goes to middle in these 1559ff308f991c647ac8e3d1f88c457119723452 and 88ec21f12cc24ac6625d5dfd21c281ef0a613f95
