### ISSUE TITLE
trying to compile gives "meson: error: unrecognized arguments: -C builddir"

### ISSUE THREAD

**Issue by RodolpheGohard** [jack-mixer/jack_mixer#108]
as per the install.md, I tried to run these:

```
meson setup builddir --prefix=/usr --buildtype=release
meson compile -C builddir
```

but the compile line fails with:
```
~/dev/jack_mixer$ meson compile -c builddir
usage: meson [-h] {setup,configure,dist,install,introspect,init,test,wrap,subprojects,help,rewrite} ...
meson: error: unrecognized arguments: -c builddir
```
removing the argument makes the compile work, with this:
`Build dir: /home/rodolphe/dev/jack_mixer/compile`

**Comment by RodolpheGohard** [comment]
Not sure if related, but I cannot run the program after compiling installing:
```
:~/dev/jack_mixer/compile$ jack_mixer
Traceback (most recent call last):
  File "/usr/local/bin/jack_mixer", line 5, in <module>
    from jack_mixer.app import main
ModuleNotFoundError: No module named 'jack_mixer'
```

**Comment by SpotlightKid** [comment]
You need `meson` >= 0.54 for the `compile` an `install ` commands. Otherwise use `ninja` directly instead.

I guess you are on debian or Ubuntu. Please see https://github.com/jack-mixer/jack_mixer/wiki/Installing-on-debian---Ubuntu

**Comment by SpotlightKid** [comment]
Added mention of the minimum meson version to `INSTALL.md` and a note referring to the above mentioned wiki page.
