### ISSUE TITLE
levels of presets are not restoring

### ISSUE THREAD

**Issue by capoei** [jack-mixer/jack_mixer#113]
I am using jack-mixer to downmix 5.1 to stereo.
I put everything but front channles to -3dB and output to -5dB but when restoring the preset all faders are at 0dB

**Comment by SpotlightKid** [comment]
please attach the preset file and your settings in `~/.config/jack_mixer`.

please also state the version of jack_mixer you are using and which Python version and which distro you are using.

**Comment by capoei** [comment]
Em dom., 14 de mar. de 2021 às 11:59, Christopher Arndt <
***@***.***> escreveu:

**Comment by SpotlightKid** [comment]
@capoei You reply shows up empty here. Please go to the ticket in you browser and attach the files there.

**Comment by capoei** [comment]
sorry

[debug_jck_mx.tar.gz](https://github.com/jack-mixer/jack_mixer/files/6137102/debug_jck_mx.tar.gz)

**Comment by SpotlightKid** [comment]
Should be fixed by #114. Please update from git test and re-open in case the problem still exists.

**Comment by capoei** [comment]
it fixed the issue
