### ISSUE TITLE
ModuleNotFoundError: No module named 'jack_mixer' - Raspberry Pi OS

### ISSUE THREAD

**Issue by albertorizzo** [jack-mixer/jack_mixer#115]
I would like to report this issue:
When I try to launch jack_mixer after the build with meson I get this message:

**Traceback (most recent call last):
  File "/usr/bin/jack_mixer", line 5, in <module>
    from jack_mixer.app import main
ModuleNotFoundError: No module named 'jack_mixer'**

Here's some additional build info:

The Meson build system
Version: 0.57.1
Source dir: /home/pi/Downloads/jack_mixer-main
Build dir: /home/pi/Downloads/jack_mixer-main/builddir
Build type: native build
Project name: jack_mixer
Project version: 15.1
C compiler for the host machine: cc (gcc 8.3.0 "cc (Raspbian 8.3.0-6+rpi1) 8.3.0")
C linker for the host machine: cc ld.bfd 2.31.1
Host machine cpu family: arm
Host machine cpu: armv7l
Dependency glib-2.0 found: YES 2.58.3 (cached)
Library m found: YES
Dependency jack found: YES 1.9.17 (cached)
Dependency jack found: YES 1.9.17 (cached)
Program python3 (gi, cairo, xdg) found: YES (/usr/bin/python3) modules: gi, cairo, xdg
Program cython found: YES (/usr/bin/cython)
Program meson_dist_cython.py found: YES (/home/pi/Downloads/jack_mixer-main/src/meson_dist_cython.py)
Found pkg-config: /usr/bin/pkg-config (0.29)
Dependency python found: YES (pkgconfig)
Configuring version.py using configuration
Program rst2man found: YES (/usr/bin/rst2man)
Configuring jack_mixer.1.rst using configuration
Program meson_dist_rst2man.py found: YES (/home/pi/Downloads/jack_mixer-main/docs/meson_dist_rst2man.py)
Program meson_postinstall.py found: YES (/home/pi/Downloads/jack_mixer-main/meson_postinstall.py)
Build targets in project: 4

jack_mixer 15.1

  Configuration
    Build jack_mixer GUI    : True
    JACK MIDI support       : True
    Debug messages (verbose): False
    Build for wheel         : False

**Comment by SpotlightKid** [comment]
See https://github.com/jack-mixer/jack_mixer/wiki/Installing-on-debian---Ubuntu

Raspian is a debian / Unbuntu variant, so the same applies.
