### ISSUE TITLE
FR: Add on-demand horizontal scrollbar to input and output channel strip pane

### ISSUE THREAD

**Issue by SpotlightKid** [jack-mixer/jack_mixer#13]
* When you have many input channels, the panel with the input channel strips can not show strips, if the window is not wide enough-  The rightmost channels may be overlapped by the output chanenls as well.

* If you have many output channels, the window width grows with the number of output channes and can't be resized to be less wide.

A solution would be to add horizontal sliders to both the input and output channel strip panes if their content becomes wider than the pane. And allow making the main window less wide even if there are many output channels.

**Comment by dsheeler** [comment]
Added output channels scrollbar.  Also added a paned widget between the input and output channel strips.  c568805562019088f063f45278c03c9d36c83a15
