### ISSUE TITLE
FR: Add option for MIDI CC behaviour: "jump to value" or "pick-up"

### ISSUE THREAD

**Issue by SpotlightKid** [jack-mixer/jack_mixer#14]
Currently, when you control a channel strip fader with a MIDI CC, the control immediately jumps to the value of the MIDI CC received. This can lead to big jumps in volume, when the position of the physical fader or pot on the MIDI controller did not match the current value of the fader in the jack_mixer channel strip.

I propose an global option to switch between to modes of behaviour for MIDI control:

- "Jump to value" (current)
- "Pick up"

In "pick up mode", the value of the fader does not change on reception of the assigned MIDI CC until a MIDI CC with the current value (maybe +/- 1-2) has been received. From then on, received MIDI CCs control the fader value directly. This prevents sudden jumps in value, because he external controller has to matched up with current value first and value changes then start from there.

**Comment by dsheeler** [comment]
Really good idea!

**Comment by dsheeler** [comment]
Check out 58a9c7224b9eabd7e7faa06a8bc63c9d5c1ab3c2.  Let me know what you think.

**Comment by synthnassizer** [comment]
+1 SpotlightKid ! Thanks dsheeler!

**Comment by dsheeler** [comment]
I improved the 'pick up' behavior quite a bit here: cd152f1366ea1508d80acfd03583d303dafa9d3e
