### ISSUE TITLE
Kubuntu 20.10 Groovy Gorilla works Ok with v17 but repo has v13 & does Not work.

### ISSUE THREAD

**Issue by juanpc2018** [jack-mixer/jack_mixer#153]
Kubuntu 20.10 repo has v13
muon or synaptic package managers
Right Channel does Not work.

Removing v13 and installing v17 manually with the method for 20.04 works ok:
https://github.com/jack-mixer/jack_mixer/wiki/Installing-on-debian---Ubuntu

downloading .deb from 
https://packages.debian.org/sid/amd64/jack-mixer/download
https://debian.pkgs.org/sid/debian-main-amd64/jack-mixer_17-1_amd64.deb.html

dependency Not meet.
does not detect proper jackd2 version.

combined with Xine and jkmeter works awesome,

P.D. i have Not tested the MIDI features.

would be interesting to be able to select different mixing algorithms...
similar can be done in DSP HW with RME HDSP 9632 + hdso-tools.

this mixer is awesome to replace Xine ac3_DownMixer,
to have more control over levels.
1&2 Front L&R
3&4 Read L&R
5&6 Center & Sub.

for people with Focusrite USB Multichanel devices in Linux. that cannot be changed to Stereo in PulseAudioVolumeControl.
and DSP cannot be controlled because the Focusrite Control SW is Windows or Mac Only.
SW works ok in Wine but does Not detect the USB interface.

Awesome, Thanks.

**Comment by SpotlightKid** [comment]
Hi, thank for the report, but I'm not sure how to react. The project does not provide debian packages and it is the responsibility of the debian package maintainers to package jack_mixer correctly.

So, unless something does not work on debian/Ubuntu when manually installing jack_mixer as described in the wiki, I'm tempted to close this ticket as invalid or "wontfix".
