### ISSUE TITLE
Remember NSM visibility on start?

### ISSUE THREAD

**Issue by mxmilkiib** [jack-mixer/jack_mixer#173]
I would wish JACK Mixer to be running in the background from startup (via RS), and I don't need it to display itself unless I actively wish to access it.

(Partly related to #17)

**Comment by crshrprt** [comment]
Isn't JACK Mixer already behaving like this in RaySession? There was a bug that emerged lately that made RaySession not remembering the optional GUI states. I reported it and was fixed really quick by @Houston4444: [fix optional-gui visibilily state not restored](https://github.com/Houston4444/RaySession/commit/44b80a1afefba7839cca21c3170b0eb44d84dde1)

**Comment by mxmilkiib** [comment]
You're right, I've checked now. I must have been hit by that bug. Thanks!
