### ISSUE TITLE
Cython compile error

### ISSUE THREAD

**Issue by ignotus666** [jack-mixer/jack_mixer#180]
Hi, I've been trying to compile the latest release but keep running into this cython error:

```
FAILED: src/_jack_mixer.c 
/usr/bin/cython3 -o src/_jack_mixer.c ../src/_jack_mixer.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    ctypedef void * jack_mixer_t
    ctypedef void * jack_mixer_channel_t
    ctypedef void * jack_mixer_output_channel_t
    ctypedef void * jack_mixer_threshold_t

    ctypedef void (*midi_change_callback)(void *) noexcept with gil
                                                 ^
------------------------------------------------------------

/home/user/jack-mixer/src/_jack_mixer.pxd:28:50: Syntax error in ctypedef statement

Error compiling Cython file:
------------------------------------------------------------
...
import enum

from _jack_mixer cimport *


cdef void midi_change_callback_func(void *userdata) noexcept with gil:
                                                   ^
------------------------------------------------------------
```

Using Mint 21.2. Maybe I'm doing something wrong but previous versions never gave me compilation problems.

**Comment by SpotlightKid** [comment]
What is the output of `cython -V` on your system?

**Comment by ignotus666** [comment]
Wow, that was quick. Here's the output:

```
Command 'cython' not found, did you mean:
  command 'cython3' from deb cython3 (0.29.28-1ubuntu3)
  command 'jython' from deb jython (2.7.2+repack1-4)
```

I definitely have 'cython3' installed though.

**Comment by SpotlightKid** [comment]
Ok, the `cython3 -V`?

**Comment by ignotus666** [comment]
`Cython version 0.29.28`

**Comment by SpotlightKid** [comment]
Ok, I only tested with Cython 0.29.36 and 3.0.5. Seems something changed in an incompatible way between your version and 0.29.36?

Does Mint have a package for Cython 3.x? If so, please try install that first and try compiling again.

Alternatively, you could install the current Cython version in to your user's dir with `python -m pip install --user --force-reinstall Cython` (depending on your Python/pip version, you might also need the `--break-system-packages` option to pip. Don't worry, you can de-install this version of Cython afterwards again with `python -m pip uninstall Cython). Make sure the `cython3` command points to this version afterwards (`hash -r; which cython3`).

Also, I just uploaded a proper source distribution archive to the GitHub release, which I unfortunately forgot before:

https://github.com/jack-mixer/jack_mixer/releases/download/release-18/jack_mixer-18.tar.xz

Can you try compiling from this? This one has a pre-generated `_jack_mixer.c` file included.

**Comment by ignotus666** [comment]
Yes, that last version compiles nicely, thanks!
