### ISSUE TITLE
open jackmixer with a specified project.

### ISSUE THREAD

**Issue by toadzroc** [jack-mixer/jack_mixer#182]
This a feature request for the ability to start jackmixer from the terminal with a specified project, something lile:

$ jackmixer -P myproject.xml

JM would then open with the project loaded, ready to go.

**Comment by ignotus666** [comment]
It can already do that. Try this:

`jack_mixer --config=PATH/TO/PROJECT`

**Comment by toadzrock** [comment]
Many thanks, that worked in both the terminal and the bash script i'm building.

Just as a matter of interest, is this and other CLI options documented anywhere? 

I'm not afraid to RTFM.

(Read The Fantastic Manual)

**Comment by ignotus666** [comment]
Glad to help. Yes, type `jack_mixer --help` in the terminal.

**Comment by toadzrock** [comment]
And  I've been looking in jackmixer., not jack_mixer.

Thanks again.

**Comment by SpotlightKid** [comment]
Or `man jack_mixer`.

**Comment by toadzrock** [comment]
Yep, the man pages are a lot more descriptive.
