### ISSUE TITLE
Autoconnect ports on project startup (possibly a feature request)

### ISSUE THREAD

**Issue by toadzrock** [jack-mixer/jack_mixer#183]
At the moment we don't seem to be able to assign external port connections to a project. Is this correct?

I'd like to start jack_mixer and have output ports autoconnect to system playback ports as an example, with that information included in the project xml file. (So we can make manual changes if required)

If this is not currently possible, can you consider this a feature request?

**Comment by SpotlightKid** [comment]
No, this is not something that `jack_mixer` itself can do currently and probably we wont't add this either.

Our recommendation is to use connection managing tools like [jack-matchmaker ](https://github.com/SpotlightKid/jack-matchmaker) (see bottom of readme there for alternatives) or [NSM](https://new-session-manager.jackaudio.org/) Session Managers like [Agordejo](https://www.laborejo.org/agordejo/) or [RaySession](https://github.com/Houston4444/RaySession) for managing and remembering connections.

**Comment by toadzrock** [comment]
Ok, thanks for the heads up.
