### ISSUE TITLE
Migrate away from appdirs

### ISSUE THREAD

**Issue by paddatrapper** [jack-mixer/jack_mixer#184]
Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1067970

Please migrate away from appdirs. It is dead upstream and is going to be removed from Debian. platformdirs is a recommended fork with a similar API that should be straightforward to migrate to. Documentation: https://platformdirs.readthedocs.io/en/latest/

**Comment by ObjectBoxPC** [comment]
From what I can tell, the appdirs APIs that this program uses are the same in platformdirs, so it would be quite literally a simple find and replace across the code as well as build scripts and localizations.

**Comment by SpotlightKid** [comment]
I'll tag a new release tomorrow or next week.

**Comment by hosiet** [comment]
@SpotlightKid It looks like we still miss a tag of v19 in https://github.com/jack-mixer/jack_mixer/tags . Tagging a release would be beneficial.

**Comment by SpotlightKid** [comment]
Yeah, sorry, I was hoping I can get PR #167 also into this release, but I guess I have postpone that. I'll do a release now.
