### ISSUE TITLE
"Remove Output Channel" removes menu entry for channel but not channel strip

### ISSUE THREAD

**Issue by SpotlightKid** [jack-mixer/jack_mixer#3]
Steps to reproduce:

* Start jack_mixer
* Add an output channel ("Mixer" -> "New Output Channel"), e.g. "Master"
  * New output channel strip appears.
* "Edit" -> "Remove Output Channel" -> "Master"
  * Output channel strip "Master" is still there
  * Jack output ports "Master L" and "Master R" are still there
  * The menu entry "Edit" -> "Remove Output Channel" -> "Master" is gone.
  * Standard output message says 'Removing channel "Master"', but that doesn't actually happen.

**Comment by SpotlightKid** [comment]
Ok, this seems to have been caused by my broken gconf installation as well, as mentioned in #6. I removed use of the GConf gobject module in my local jack_mixer installation (as in the [jack_mixer AUR package](https://aur.archlinux.org/packages/jack_mixer-git/) and the problem is gone.

Feel free to close this unless you are somehow able to reproduce it.

**Comment by dsheeler** [comment]
Removed gconf in 4c1f7906f7860e78605c04554601cff2af3283af
