### ISSUE TITLE
No mixer channel strips or submenu text

### ISSUE THREAD

**Issue by mxmilkiib** [jack-mixer/jack_mixer#37]
![image](https://user-images.githubusercontent.com/108225/87211340-f83f1c00-c310-11ea-9dec-f26800d46b32.png)

**Comment by mxmilkiib** [comment]
This is when the jack_mixer is visible but still says x for not-visible in Argodejo.

When I make it a tick, the channels and menu text appear.

The "double line" in the middle, when the channel strips appear, the strips are on the left side, and I can drag it left and right, with the right side being blank and covering up the strips.

**Comment by dsheeler** [comment]
Think I fixed this one ac3f7b6208dcc92d8530980a98c077da0ce5e198.  Can you confirm?  jack_mixer should not be visible when argodejo says x for not-visible anymore, as well.

**Comment by mxmilkiib** [comment]
Confirmed.
