### ISSUE TITLE
Option for quit confirmation dialog?

### ISSUE THREAD

**Issue by mxmilkiib** [jack-mixer/jack_mixer#40]

**Comment by dsheeler** [comment]
Do you mean to always show a quit confirm dialog?  Or to have a quit confirm dialog be optional?

**Comment by mxmilkiib** [comment]
I realise this is related to my second comment on #17. I just kept closing the main window, but it quit the app, rather than hiding it. Having the app not quit on closing its window would be preferable.

**Comment by mxmilkiib** [comment]
When under NSM anyway. When not under NSM, a confirm quit (or close to tray) would be nice

**Comment by SpotlightKid** [comment]
jack_mixer, when running under NSM, now only hides its UI, when its window is closed or the "Hide" menu entry is selected (replaces "Quit" when under NSM) (#53).

There's a new option in the global settings to always ask for confirmation when quitting either via the menu or by closing the window (#54).

jack_mixer *should* always ask for confirmation before quitting, when the current mixer setup has changed and has not been saved, regardless of the confirm_quit option, but that is not implemented yet.

@mxmilkiib Care to test?

**Comment by mxmilkiib** [comment]
Yes, this works, thank you :)
