### ISSUE TITLE
Compact channel width mode?

### ISSUE THREAD

**Issue by mxmilkiib** [jack-mixer/jack_mixer#44]
I'm running out of mixer space a bit. How about a mode that narrows the width of each channel strip down to about half what it is now?

**Comment by mxmilkiib** [comment]
Just a note also that I'm back to the standard widgets for the faders, as I prefer the ability to grab onto the channel anywhere, rather than the snap action of the custom one.

**Comment by dsheeler** [comment]
I was thinking it would be possible to remove the  control group controls (pre/post, mute, solo buttons) from the input channels through a preference option.  Would we then want to make them accessible some other way?  Like hovering over the channel label or right clicking the label for a dialog?  Any other suggestions?

**Comment by SpotlightKid** [comment]
(Reposted from a private IRC conversation)

We could define a small display style for channels, which removes the control group label and makes the balance slider less wide or removes it. Switching between wide and narrow display style could be a) via the channel properties dialog or b) a small icon button next to the channel name, maybe? Also add menu entries to expand or collapse all channels.

Maybe it would be possible to overlay the meter with the fader?

**Comment by dsheeler** [comment]
1e34529c1d9c5e8238820f0c0e63f7b4cd8e81e8 is a start.

**Comment by SpotlightKid** [comment]
That and a way to expand/shrink individual channels is maybe all that is needed?

**Comment by dsheeler** [comment]
Control-click on a channel label and it toggles wide/narrow mode.  Does that work?  Saves putting a button, but I don't know if that's as good as a button. Maybe I need a tooltip for labels? Maybe I should add via the properties dialog, too?

**Comment by SpotlightKid** [comment]
This has been implemented in 1e34529c1d9c5e8238820f0c0e63f7b4cd8e81e8 and improved in #48 and #68. use the menu or Ctrl + left click on a channel header to shrink / expand it.

A possible further enhancement would be a UI element in each channel strip to shrink/expand it.  But that should be another issue.
