### ISSUE TITLE
Inaccurate wording in New Channel dialog ("MIDI Control Channels")

### ISSUE THREAD

**Issue by SpotlightKid** [jack-mixer/jack_mixer#5]
The group of the lower four control rows in the "New Channel" dialog is labelled "MIDI Control Channels", however there is no such thing. There are MIDI "Channels" and there are MIDI "Control Change" (aka "Controller Change" or simply "Controller") messages.

Since jack_mixer does not actually let the user set the MIDI *channel*, on which MIDI *control changes* are recognized (it seems to recognize them on *all* channels), the wording is inaccurate and misleading.

IMHO it should be labelled "MIDI Control Changes" or "MIDI Controllers", though the former is more precise.

**Comment by dsheeler** [comment]
811f47b8d2b5ef9c61f66d9944b3cf7c82ed2a35

**Comment by dsheeler** [comment]
Changed to "MIDI Control Changes"
