### ISSUE TITLE
make it possible to successfully configure jack_mixer without python

### ISSUE THREAD

**Issue by synthnassizer** [jack-mixer/jack_mixer#51]
... in which case only the c application can be build. 
Some times a headless mixer in embedded devices is more than enough and python maybe an overkill especially if you are not going to use it...

**Comment by synthnassizer** [comment]
If accepted, the pull request #83 takes care of this feature request

**Comment by SpotlightKid** [comment]
Implemented in f14c177f5bfc4681cd09c64c1a4c4da08f9c6f90.

**Comment by SpotlightKid** [comment]
Thanks, @synthnassizer !
