### ISSUE TITLE
[BUG] color/writings issue

### ISSUE THREAD

**Issue by trebmuh** [jack-mixer/jack_mixer#56]
With some color, the writings aren't readable.

Example:
![jack_mixer-color_issue](https://user-images.githubusercontent.com/8705846/91099880-68f18c00-e664-11ea-9a1a-2306c4e06cfc.png)

**Comment by dsheeler** [comment]
Are you using the newest version?  If so, there is a color chooser for output colors accessible when you edit the channel

**Comment by trebmuh** [comment]
Yes I'm using the 13 version.
Yes I know that one can choose the colour (that is the way I've chosen red/yellow/white/black here).

I might be better to precise my bug then: a proposition to correct the bug is that the colour of the writings could be:

1. chosen by the user with a colour-picker (as the colour of the background is right now), which means a second colour-picker option
2. automagically chosen by the program to match the background program. Ie, as examples:

- if the user is choosing "black" for the background, then the writing colour is automatically chosen to "white"
- if the user is choosing "white" for the background, then the writing colour is automatically chosen to "black"

I've seen that on other program but can't remember which ones at the top of my head right now. I' hope you get the idea, if not, please feel free to ask.

**Comment by frederic-peters** [comment]
For the record I already have code to pick black or white,

```python
def get_foreground_colour(background_colour):
    """Calculates the luminance of the given colour (six hexadecimal digits)
       and returns an appropriate foreground colour."""
    # luminance coefficients taken from section C-9 from
    # http://www.faqs.org/faqs/graphics/colorspace-faq/
    brightess = int(background_colour[0:2], 16) * 0.212671 + \
            int(background_colour[2:4], 16) * 0.715160 + \
            int(background_colour[4:6], 16) * 0.072169
    if brightess > 128:
        fg_colour = 'black'
    else:
        fg_colour = 'white'
    return fg_colour
```

I'll have a look at integrating it.

**Comment by trebmuh** [comment]
Nice.

**Comment by trebmuh** [comment]
Awesome, that fixed it :+1:
