### ISSUE TITLE
internationalization

### ISSUE THREAD

**Issue by trebmuh** [jack-mixer/jack_mixer#57]
I'd be great to provide a way for JiM to be translatable.
I don't know how to code that, but I'd be happy to provide a French translation when it's done.

* [x] Integrate gettext
* [x] Mark translatable strings
* [x] Extract messages catalog template
* [x] Add scripts to manage message files
* [x] Add reference translation (German)
* [x] Update meson build setup to build and install `*.mo` files
* [x] Add instructions on adding / updating a translation somewhere (new contributing guide, see #118) 
* [x] Add global setting for language to use #121

**Comment by frederic-peters** [comment]
Sure but this will require changes to the build system, better to wait for the switch to Meson (work in progress in pull request #29)

**Comment by trebmuh** [comment]
OK, thanks for the answer, I'll wait then.
Feel free to ping me if needed.

**Comment by SpotlightKid** [comment]
It'll also require small (though not compliecated) changes in many places in the GTK code.

I18N is something that's been on my internal wish / to do list already.

**Comment by trebmuh** [comment]
Pinging as a friendly reminder here.
Has the switch to meson progressed?

**Comment by SpotlightKid** [comment]
I'm sorry to say, no. I can't speak for the other developers, but as for myself, I currently need to be concentrating on the business side of life, and I'm afraid I probably won't be able to work on jack-mixer before the next year.

**Comment by trebmuh** [comment]
Fair enough.
Thanks for answering.

**Comment by SpotlightKid** [comment]
All done now.
