### ISSUE TITLE
Add man page

### ISSUE THREAD

**Issue by trebmuh** [jack-mixer/jack_mixer#61]
[Debian has made one years ago](https://salsa.debian.org/multimedia-team/jack-mixer/-/blob/master/debian/jack_mixer.1). It probably needs to be updated before getting it in here (upstream).

**Comment by SpotlightKid** [comment]
In my [jack-select](https://github.com/SpotlightKid/jack-select) project, I write the man page in ReStructuredText and convert it with `rst2man` (part of `docutuils`), which works nicely.

**Comment by SpotlightKid** [comment]
I've created a draft PR with a stub for a man page for `jack_mixer` as a RestructuredText source.

Help welcome in fleshing out the content or creating a man page for `jack_mix_box` from this template!

**Comment by trebmuh** [comment]
Following #93, you should add in the description session:
> It is designed to work with the NSM session management protocol.

**Comment by SpotlightKid** [comment]
> It is designed to work with the NSM session management protocol.

That sounds like it can only be used sensibly with NSM, but that's not true.

Something like this sounds more accurate:

> It is compatible with the NSM session management protocol. When running as an NSM client, the mixer layout and current state will be saved in the NSM session.

**Comment by trebmuh** [comment]
agreed
