### ISSUE TITLE
Include NEWS update text in release messages?

### ISSUE THREAD

**Issue by mxmilkiib** [jack-mixer/jack_mixer#72]
I'm working on https://libreav.org/updates currently, and was wondering if I could request that the NEWS file update text gets used in the release message itself so that it can be aggregated via the releases.atom feed?

**Comment by SpotlightKid** [comment]
This ok?

https://github.com/jack-mixer/jack_mixer/releases/tag/release-14

**Comment by mxmilkiib** [comment]
That's awesome, thank you

**Comment by mxmilkiib** [comment]
Might it be possible to get the release notes for prior versions of jack_mixer in the GH release messages?

**Comment by SpotlightKid** [comment]
Done for releases 11, 12 and 13. Release 10 was back in 2014, so we won't update the releases for this or any prior versions.
