### ISSUE TITLE
Solo feature is not working as expected

### ISSUE THREAD

**Issue by moonshaadow** [jack-mixer/jack_mixer#96]
I have two stereo inputs tracks (named input 1 and 2), one stereo output track (called Master). Master, direct outputs and mon all routed in metering tool to check.

Two different signals are routed to input 1 and input 2. Input 2 is monitored ( by MON button)
Test of SOLO button on Input 1 :
   - As expected, only Signal 1 passes through Master
   - Signal 2 is still passing through direct output 2, and mon if mon is selected on track 2. I don't know if this is wanted or not. It first seems weird to me , but after all it is a direct output and might not be influenced by solo.
   - The freaky thing : Signal 1 is now passing through direct out 2 and mon (and all direct outputs if there are more tracks)

**Comment by SpotlightKid** [comment]
Thanks for the report. Let's make sure you are able to run and an up-to-date version from git repo checkout first (see #81), then revisit this.

**Comment by moonshaadow** [comment]
According to #81, I run an up-to-date version now. Issue is still here.

**Comment by SpotlightKid** [comment]
> Signal 2 is still passing through direct output 2, and mon if mon is selected on track 2. I don't know if this is wanted or not. It first seems weird to me , but after all it is a direct output and might not be influenced by solo.

Yes, that is the intended and IMHO logical behavior. The solo state only influenced regular output channels.

**Comment by SpotlightKid** [comment]
I was able to reproduce this. Enabling channel solo on channel "input 1" adds the channel's output  to the signal at direct outs of channel "input 2". That shouldn't happen. I'll investigate.
