### ISSUE TITLE
Prevent automatic creation of pass-through outputs for every input

### ISSUE THREAD

**Issue by scruloose** [jack-mixer/jack_mixer#98]
Sorry if there's already an option for this that I'm overlooking. I'm no sound engineer, and I'm pretty new to JACK in general.

I'm using jack-mixer in conjunction with Qjackctl to selectively pipe audio from various apps and a mic to different outputs. Whenever I create an input channel in jack-mixer, eg `HW mic in`, I see in Qjackctl's graph view that the new input has appeared in the jack-mixer node as expected, but a new output called `HW mic in Out` *also* appears. I'm guessing the use-case for this is if you want to grab the individual channel but still take advantage of the volume control provided by jack-mixer's input fader (because otherwise, you'd just connect the source node directly to as many destinations as you want rather than go through jack-mix at all, right?)…

For my use-case though, I have no use for those pass-through outputs, so they just make jack-mixer's node in the Qjackctl graph twice as tall as it needs to be, and add confusion when connecting jack-mixer's mixed outputs to their appropriate destinations. I don't see any way to prevent the creation of these unwanted outputs, or delete them, or hide them, or anything.

I assume this behaviour is the intended default, but it would be really nice to have at least a ticky-box in the "New input channel" dialog box to prevent it. Ideally, I'd like a setting in Preferences to set the default on or off as well.

**Comment by SpotlightKid** [comment]
Thanks for your suggestions. This would be certainly doable, but require a lot of adaptions in the lower layer of the application code. I am afraid that there are currently more pressing matters to get to before this can be addressed.

But as always, pull requests are welcome.

**Comment by scruloose** [comment]
Fair enough. It's definitely a wishlist item; I was hoping it wouldn't be a whole lot of work to implement.

The odds of this being within my coding ability are... slim.  ;-)

Maybe some day.

**Comment by SpotlightKid** [comment]
Turns out, this could be solved entirely in the frontend code.
