### ISSUE TITLE
jack_mixer_cc - CLI for jack_mixer 

### ISSUE THREAD

**Issue by sen87** [jack-mixer/jack_mixer#99]
Hi, some time ago I created a script for jack_mixer that provides CLI access to all channel volume controls.
I used it primarily to control volume via keyboard shortcuts and to control monitoring volume from another system on my local network.

I've just updated it to work with the [Fix MIDI control and output](https://github.com/jack-mixer/jack_mixer/pull/95) commit by SpotlightKid and uploaded it to GitHub. It now sets mute properly (instead of working with the channel volume) and can toggle solo mode.

https://github.com/sen87/jack_mixer_cc

This is of course not a jack_mixer issue. I just wanted to share it in case someone else has a use for it.

**Comment by SpotlightKid** [comment]
FYI, #95 has been merged now.

**Comment by synthnassizer** [comment]
Nice feature!
thank you Sen

**Comment by SpotlightKid** [comment]
I started a wiki page and made a link to your project:

https://github.com/jack-mixer/jack_mixer/wiki
